"""add source_candidate_id to knowledge_items

Revision ID: 7e02aa099c02
Revises: 
Create Date: 2026-03-25 14:42:24.271059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e02aa099c02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('source_candidate_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_knowledge_items_source_candidate_id'), 'knowledge_items', ['source_candidate_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_items', 'answer_candidates', ['source_candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_items', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_items_source_candidate_id'), table_name='knowledge_items')
    op.drop_column('knowledge_items', 'source_candidate_id')
    # ### end Alembic commands ###
